FanMatch/Models/Entities/Match.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FanMatch.Models
{
    public class Match
    {
        public int Id { get; set; }


        public virtual Person Writer { get; set; }


        public virtual Person Reader { get; set; }



        public virtual Project Project { get; set; }
        public virtual Fandom Fandom { get; set; }
        /// <summary>
        /// Is this match not allowed?
        /// </summary>
        public bool IsBanned { get; set; }

        /// <summary>
        /// Is this match required?
        /// </summary>
        public bool IsLocked { get; set; }
    }
}

FanMatch/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FanMatch.Models;
using FanMatch.Models.Data_Access;
using FanMatch.ViewModels;

namespace FanMatch.Controllers
{

    public enum MatchAction
    {
        Clear,
        Ban,
        Lock
    }

        [HackAuth]
    public class MatchController : Controller
    {
        private readonly Func<IMatchRepository> matchRepo;
        private readonly Func<IPersonRepository> personRepo;

        public MatchController(Func<IMatchRepository> matchRepo, Func<IPersonRepository> personRepo) {
            this.matchRepo = matchRepo;
            this.personRepo = personRepo;
        }

        public MatchController() : this(() => new MatchRepository(), () => new PersonRepository()) { }

        //
        // GET: /Match/

        public ActionResult Index()
        {
            using (var pRepo = this.personRepo())
            using (var mRepo = this.matchRepo())
            {
                var allPeople = pRepo.GetAll();
                var matcher = new Matcherizer(allPeople, mRepo.LoadAll());
                var matches = matcher.Matcherize();
                return View(new MatchResultViewModel(matches, allPeople));
            }
        }

        public ActionResult ChangeMatchStatus(int reader, int writer, MatchAction action)
        {
            using (var mRepo = this.matchRepo())
            {
                switch (action)
                {
                    case MatchAction.Ban:
                        mRepo.Ban(reader, writer);
                        break;
                    case MatchAction.Lock:
                        mRepo.Lock(reader, writer);
                        break;
                    case MatchAction.Clear:
                        mRepo.Clear(reader, writer);
                        break;
                }
            }
            return RedirectToAction("Index");
        }

    }
}

FanMatch/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FanMatch.Models;

namespace FanMatch.Controllers
{

    [HackAuth]
    public class PersonController : Controller
    {
        public class PersonEditorViewModel
        {
            public Person Person;
            public IEnumerable<Fandom> AllFandoms;
        }

        private FanMatchDb db = new FanMatchDb();

        //
        // GET: /Person/

        public ViewResult Index()
        {
            return View(db.People.ToList());
        }

        //
        // GET: /Person/Details/5

        public ViewResult Details(int id)
        {
            Person person = db.People.Find(id);
            return View(person);
        }


        public ActionResult New(string name)
        {
            var person = new Person { Name = name };
            db.People.Add(person);
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = person.Id });
        }

        public ViewResult DestroyAllHumans()
        {
            return View();
        }

        public ActionResult DestroyAllHumansConfirm()
        {
            var matches = db.Matches;
            foreach (var match in matches)
            {
                db.Matches.Remove(match);
            }

            var people = db.People;
            foreach (var person in people)
            {
                db.People.Remove(person);
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        
        //
        // GET: /Person/Edit/5
 
        public ActionResult Edit(int id)
        {
            Person person = db.People.Find(id);
            
            var allFandoms = db.Fandoms.ToList();
            var model = new PersonEditorViewModel
            {
                Person = person,
                AllFandoms = allFandoms
            };
            return View(model);
        }

        public PartialViewResult _PersonTag(int id)
        {
            var person = db.People.Find(id);
            return PartialView(person);
        }

        public class PersonWebModel
        {
            public String Name { get; set; }
            public bool IsReader { get; set; }
            public bool IsWriter { get; set; }
            public bool CanMatchMultiple { get; set; }
            public List<InteractionPreference> InteractionPreferences { get; set; }
        }

        [HttpPost]
        public void Save(int id, PersonWebModel data)
        {
            var person = db.People.Find(id);

            person.Name = data.Name;
            person.IsReader = data.IsReader;
            person.IsWriter = data.IsWriter;
            person.CanMatchMultiple = data.CanMatchMultiple;
            person.SetInteractionPreference(data.InteractionPreferences ?? Enumerable.Empty<InteractionPreference>());

            var entry = db.Entry(person);
            entry.State = EntityState.Modified;

            db.SaveChanges();
        }


        //
        // GET: /Person/Delete/5
 
        public ActionResult Delete(int id)
        {
            Person person = db.People.Find(id);
            return View(person);
        }

        //
        // POST: /Person/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Person person = db.People.Find(id);
            db.People.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult AddFandom(int personId, int fandomId)
        {
            var addedFandom = db.Fandoms.Find(fandomId);
            AddFandomsToPerson(personId, new[] { addedFandom });

            return Json(new FandomInfo(addedFandom));
        }

        private void AddFandomsToPerson(int personId, IEnumerable<Fandom> addedFandoms)
        {
            var person = db.People.Find(personId);
            var entry = db.Entry(person);
            entry.State = EntityState.Modified;
            entry.Collection(e => e.Fandoms).Load();

            foreach (var fandom in addedFandoms)
            {
                person.Fandoms.Add(fandom);
            }


            db.SaveChanges();
        }

        [HttpPost]
        public JsonResult AddFandoms(int personId, IEnumerable<int> fandomIds)
        {
            var addedFandoms = db.Fandoms.Where(f => fandomIds.Contains(f.Id));
            AddFandomsToPerson(personId, addedFandoms);

            var addedFandomInfos = new List<FandomInfo>();
            foreach (var fandom in addedFandoms)
            {
                addedFandomInfos.Add(new FandomInfo(fandom));
            }

            return Json(addedFandomInfos);
        }

        [HttpPost]
        public void RemoveFandom(int personId, int fandomId)
        {
            var person = db.People.Find(personId);
            var entry = db.Entry(person);
            entry.State = EntityState.Modified;
            entry.Collection(e => e.Fandoms).Load();

            person.Fandoms = person.Fandoms.Where(f => f.Id != fandomId).ToList();

            db.SaveChanges();
        }

        [HttpPost]
        public JsonResult CreateFandomAndAddToPerson(string name, int personId)
        {
            var fandom = new Fandom { Name = name };
            db.Fandoms.Add(fandom);
            AddFandomsToPerson(personId, new[] { fandom });
            return Json(new FandomInfo(fandom));
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }

    public class FandomInfo
    {
        public FandomInfo(Fandom addedFandom)
        {
            this.Id = addedFandom.Id;
            this.Name = addedFandom.Name;
            this.Population = addedFandom.People.Count();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int Population { get; set; }
    }
}

FanMatch/Views/Match/Index.cshtml
@model FanMatch.ViewModels.MatchResultViewModel
@using FanMatch.Models;

@{
    ViewBag.Title = "Match Results";
}

@functions {
    public string IpOverlapColor(Person a, Person b)
    {
        return a.InteractionPreferenceDistance(b) == 0 ? "green" : "yellow";
    }
}

<h1>@ViewBag.Title</h1>


<script>

    function DrawLine(x1, y1, x2, y2) {

            if (y1 < y2) {
                var pom = y1;
                y1 = y2;
                y2 = pom;
                pom = x1;
                x1 = x2;
                x2 = pom;
            }

            var a = Math.abs(x1 - x2);
            var b = Math.abs(y1 - y2);
            var c;
            var sx = (x1 + x2) / 2;
            var sy = (y1 + y2) / 2;
            var width = Math.sqrt(a * a + b * b);
            var x = sx - width / 2;
            var y = sy;

            a = width / 2;

            c = Math.abs(sx - x);

            b = Math.sqrt(Math.abs(x1 - x) * Math.abs(x1 - x) + Math.abs(y1 - y) * Math.abs(y1 - y));

            var cosb = (b * b - a * a - c * c) / (2 * a * c);
            var rad = Math.acos(cosb);
            var deg = (rad * 180) / Math.PI

        htmlns = "http://www.w3.org/1999/xhtml";
            div = document.createElementNS(htmlns, "div");
            div.setAttribute('style', 'border:1px dashed #ccc;width:' + width + 'px;height:0px;-moz-transform:rotate(' + deg + 'deg);-webkit-transform:rotate(' + deg + 'deg);position:absolute;top:' + y + 'px;left:' + x + 'px;');
            div.setAttribute('class', 'fandomLine');

            document.body.appendChild(div);

        }

        function ElementLine($start, $end) {
            var startOffset = $start.offset();
            var endOffset = $end.offset();
            var xStart = startOffset.left + $start.width() / 2.0
            var xEnd = endOffset.left + $end.width() / 2.0
            var yStart, yEnd;
            if (startOffset.top < endOffset.top) {
                yStart = startOffset.top + $start.height();
                yEnd = endOffset.top;
            } else if (startOffset.top == endOffset.top) {
                yStart = startOffset.top;
                yEnd = endOffset.top;
            } else {
                yStart = startOffset.top;
                yEnd = endOffset.top + $end.height();
            }

            DrawLine(xStart, yStart, xEnd, yEnd);
        }

    $(function () {
        $('table .btn').on('click', function (e) {
            e.preventDefault();
            var tr = $(this).closest("tr");
            $("#reader").val(tr.data('reader-id'));
            $("#writer").val(tr.data('writer-id'));
            var action;
            if ($(this).is('.lock')) {
                action = "@FanMatch.Controllers.MatchAction.Lock";
            }
            else if ($(this).is('.ban')) {
                action = "@FanMatch.Controllers.MatchAction.Ban";
            }
            else {
                action = "@FanMatch.Controllers.MatchAction.Clear";
            }
            $("#matchAction").val(action);
            $("#ChangeMatchStatus").submit();
        });

        $(".manualSelect").on("change", function () {
            var select = this;
            var personId = $(select).val();
            var target = $(select).data("tag-placeholder");
            if (!personId) {
                $(target).html("");
                $("#manualSubmit").addClass("disabled");
                return;
            }

            if (_.every($(".manualSelect"), function (e) { return $(e).val(); })) {
                $("#manualSubmit").removeClass("disabled");
            }

            $.get("@Url.Action("_PersonTag", "Person")",
                { id: personId },
                function (data) {
                    $(target).html(data);
            },
                "html");

        });

        $(document).keyup(function (e) {

            if (e.keyCode === 27) {
                $(".fandomLine").remove();
            }

        });

        $("#main").on("mouseover", ".personTag", function () {
            $(".fandomLine").remove();
            var start = $(this).find(".fandom-tip");
            var startTd = $(this).closest("td");
            $(".fandom-tip").each(function () {
                var end = this;
                if (start == end) { return true; }
                var startName = $(start).closest(".personTag").find(".personName");
                var endName = $(end).closest(".personTag").find(".personName");

                if (startName.text() == endName.text()) { return true; }
                var endTd = $(end).closest("td");
                if (endTd.data("artist-type") == startTd.data("artist-type"))
                {
                    return true;
                }

                var startFandoms = $(start).data("fandoms");
                var endFandoms = $(end).data("fandoms");
                if (_.intersect(startFandoms, endFandoms).length > 0) {
                    ElementLine(startName, endName);
                }
            });
        });


    });
</script>

<style type="text/css">
    .match-table th {
        width: 20%;
    }
</style>

<form method="post" id="ChangeMatchStatus" action="@Url.Action("ChangeMatchStatus")">
    <input type="hidden" name="reader" id="reader" />
    <input type="hidden" name="writer" id="writer"/>
    <input type="hidden" name="action" id="matchAction"/>
</form>

<div class="row-fluid">
<form method="post" class="well well-small span4"  action="@Url.Action("ChangeMatchStatus")">
    <fieldset>
    @Html.Hidden("action", "Lock")
    <legend>Manual match</legend>
    <label for="reader">Reader: <span id="readerTagPlaceholder"></span></label>
    <select name="reader"class="manualSelect"  data-tag-placeholder="#readerTagPlaceholder">
        <option></option>
        @foreach (var person in Model.AllPeople.Where(p => p.IsReader).OrderBy(p => p.Name))
        {
            <option value="@person.Id">@person.Name</option>
        }
    </select>

    <label for="writer">Writer: <span id="writerTagPlaceholder"></span></label>
    <select name="writer" class="manualSelect" data-tag-placeholder="#writerTagPlaceholder">
        <option></option>
        @foreach (var person in Model.AllPeople.Where(p => p.IsWriter).OrderBy(p => p.Name))
        {
            <option value="@person.Id">@person.Name</option>
        }
    </select>

    <br />

    <button type="submit" class="btn btn-success disabled" id="manualSubmit" value="Lock"><i class="glyphicon glyphicon-lock"></i> Lock</button>
        </fieldset>
</form>
    </div>

<h3>Locked</h3>


<table class="table table-bordered table-striped match-table">
    <tr>
        <th>Reader</th>
        <th>Writer</th>
        <th>IP Match</th>
        <th>Fandom(s)</th>
        <th>Unlock</th>
        <th>Ban</th>
    </tr>

    @foreach (var match in Model.Locked)
    {
       <tr data-reader-id="@match.ReaderId" data-writer-id="@match.WriterId">
            <td data-artist-type="reader">@Html.Partial("_PersonTag", match.Reader)</td>
            <td data-artist-type="writer">@Html.Partial("_PersonTag", match.Writer)</td>
            <td style="background-color: @(IpOverlapColor(match.Reader, match.Writer))"></td>
            <td>@match.FandomIntersection()</td>
            <td><button type="button" class="btn unlock"><span class="glyphicon glyphicon-lock"></span></button></td>
            <td><button type="button" class="btn btn-danger ban"><span class="glyphicon glyphicon-ban-circle"></span></button></td>
        </tr>
    }
</table>

<h3>Matched</h3>

<table class="table table-bordered table-striped match-table">
    <tr>
        <th>Reader</th>
        <th>Writer</th>
        <th>IP Match</th>
        <th>Fandom(s)</th>
        <th>Lock</th>
        <th>Ban</th>
    </tr>
    @foreach (var match in Model.Matches)
    {
       <tr data-reader-id="@match.ReaderId" data-writer-id="@match.WriterId">
            <td data-artist-type="reader">@Html.Partial("_PersonTag", match.Reader)</td>
            <td data-artist-type="writer">@Html.Partial("_PersonTag", match.Writer)</td>
            <td style="background-color: @(IpOverlapColor(match.Reader, match.Writer))"></td>
            <td>@match.FandomIntersection()</td>
            <td><button type="button" class="btn btn-success lock"><span class="glyphicon glyphicon-lock"></span></button></td>
            <td><button type="button" class="btn btn-danger ban"><span class="glyphicon glyphicon-ban-circle"></span></button></td>
        </tr>
    }
</table>

@if (Model.UnmatchedPeople.Any())
    {

    <h3>Unmatched</h3>

    @Html.Partial("_PersonTable", Model.UnmatchedPeople)



}


<h3>Banned</h3>

<table class="table table-bordered table-striped match-table">
    <tr>
        <th>Reader</th>
        <th>Writer</th>
        <th>IP Match</th>
        <th>Fandom(s)</th>
        <th>Lock</th>
        <th>Unban</th>
    </tr>
    @foreach (var match in Model.Banned)
    {
       <tr data-reader-id="@match.ReaderId" data-writer-id="@match.WriterId">
            <td data-artist-type="reader">@Html.Partial("_PersonTag", match.Reader)</td>
            <td data-artist-type="writer">@Html.Partial("_PersonTag", match.Writer)</td>
            <td style="background-color: @(IpOverlapColor(match.Reader, match.Writer))"></td>
            <td>@match.FandomIntersection()</td>
            <td><button type="button" class="btn btn-success lock"><span class="glyphicon glyphicon-lock"></span></button></td>
            <td><button type="button" class="btn unban"><span class="glyphicon glyphicon-ban-circle"></span></button></td>
        </tr>
    }
</table>

FanMatch/Views/Match/_PeopleDropdown.cshtml
@model IEnumerable<FanMatch.Models.Person>

<select>
    @foreach (var person in this.Model)
    {
        <option value="@person.Id">@person.Name</option>
    }

</select>